import turtle as trtl


tr = trtl.Turtle()
wn = trtl.Screen()

# mid
def line3():
    tr.pensize(5)
    tr.speed(50)
    tr.penup()
    tr.goto(-500,0)
    tr.pendown()
    tr.setheading(-86)
    tr.circle(100, -150)
    tr.penup()
    tr.goto(-317,64)
    tr.pendown()
    tr.goto(-200,-200)
    tr.penup()
    tr.goto(-200,-200)
    tr.pendown()
    tr.setheading(-70)
    tr.circle(100, 150)
    tr.penup()
    tr.goto(-10,-190)
    tr.pendown()
    tr.setheading(-99)
    tr.circle(80, -90)
    tr.setheading(6)
    tr.circle(-80, 70)
    tr.setheading(-70)
    tr.circle(80, 70)
    tr.setheading(0)
    tr.forward(260)
    # base
    tr.pensize(1)
    tr.penup()
    tr.goto(-500,10)
    tr.pendown()
    tr.goto(-500,-400)
    tr.penup()
    tr.goto(-400,105)
    tr.pendown()
    tr.goto(-400,-400)
    tr.penup()
    tr.goto(-300,30)
    tr.pendown()
    tr.goto(-300,-400)
    tr.penup()
    tr.goto(-200,-205)
    tr.pendown()
    tr.goto(-200,-400)
    tr.penup()
    tr.goto(-100,-270)
    tr.pendown()
    tr.goto(-100,-400)
    tr.penup()
    tr.goto(-100,-265)
    tr.pendown()
    tr.goto(-100,-400)
    tr.penup()
    tr.goto(0,-170)
    tr.pendown()
    tr.goto(0,-400)
    tr.penup()
    tr.goto(100,-125)
    tr.pendown()
    tr.goto(100,-400)
    tr.penup()
    tr.goto(200,-210)
    tr.pendown()
    tr.goto(200,-400)
    tr.penup()
    tr.goto(300,-220)
    tr.pendown()
    tr.goto(300,-400)
    tr.penup()
    tr.goto(400,-220)
    tr.pendown()
    tr.goto(400,-400)
    tr.penup()
    tr.goto(500,-220)
    tr.pendown()
    tr.goto(500,-400)
    # floor
    tr.pensize(5)
    tr.goto(-500,-400)
    # vehicle
    v = trtl.Turtle()
    vehicle = ("1.1.9/ihateyou (1).gif")
    wn.addshape(vehicle)
    v.shape(vehicle)
    v.penup()
    v.goto(-500,20)
    v.pensize(0.25)
    v.speed(4)
    v.setheading(-86)
    v.circle(100, -140)
    v.goto(-317,84)
    v.goto(-200,-160)
    v.goto(-200,-180)
    v.setheading(-70)
    v.circle(100, 150)
    v.goto(-10,-170)
    v.setheading(-99)
    v.circle(80, -90)
    v.setheading(6)
    v.circle(-80, 70)
    v.setheading(-70)
    v.circle(80, 70)
    v.setheading(0)
    v.forward(260)
#intense
def line2():
    tr.pensize(5)
    tr.speed(70)
    tr.penup()
    tr.goto(-500,200)
    tr.pendown()
    tr.setheading(-86)
    tr.circle(100, -150)
    tr.penup()
    tr.goto(-317,264)
    tr.pendown()
    tr.goto(-200,0)
    tr.setheading(-70)
    tr.circle(100, 75)
    tr.setheading(0)
    tr.forward(60)
    tr.setheading(0)
    tr.circle(100,70)
    tr.forward(40)
    tr.setheading(90)
    tr.circle(80,160)
    tr.setheading(90)
    tr.forward(-30)
    tr.setheading(-90)
    tr.circle(100,70)
    tr.forward(50)
    tr.setheading(0)
    tr.forward(50)
    tr.setheading(0)
    tr.circle(-100,80)
    tr.setheading(0)
    tr.goto(180,-200)
    tr.setheading(-90)
    tr.circle(100,80)
    tr.setheading(0)
    tr.forward(240)
    # base
    tr.pensize(1)
    tr.penup()
    tr.goto(-500,200)
    tr.pendown()
    tr.goto(-500,-400)
    tr.penup()
    tr.goto(-400,305)
    tr.pendown()
    tr.goto(-400,-400)
    tr.penup()
    tr.goto(-300,220)
    tr.pendown()
    tr.goto(-300,-400)
    tr.penup()
    tr.goto(-200,0)
    tr.pendown()
    tr.goto(-200,-400)
    tr.penup()
    tr.goto(-100,-65)
    tr.pendown()
    tr.goto(-100,-400)
    tr.penup()
    tr.goto(0,-65)
    tr.pendown()
    tr.goto(0,-400)
    tr.penup()
    tr.goto(100,-80)
    tr.pendown()
    tr.goto(100,-400)
    tr.penup()
    tr.goto(200,-260)
    tr.pendown()
    tr.goto(200,-400)
    tr.penup()
    tr.goto(300,-300)
    tr.pendown()
    tr.goto(300,-400)
    tr.penup()
    tr.goto(400,-300)
    tr.pendown()
    tr.goto(400,-400)
    tr.penup()
    tr.goto(500,-300)
    tr.pendown()
    tr.goto(500,-400)
    # floor
    tr.pensize(5)
    tr.penup()
    tr.goto(-500,-400)
    tr.pendown()
    tr.goto(500,-400)
    # vehicle
    v = trtl.Turtle()
    vehicle = ("1.1.9/ihateyou (1).gif")
    wn.addshape(vehicle)
    v.shape(vehicle)
    v.speed(8)
    v.penup()
    v.goto(-500,220)
    v.setheading(-86)
    v.circle(100, -150)
    v.goto(-317,284)
    v.goto(-200,20)
    v.setheading(-70)
    v.circle(100, 75)
    v.setheading(0)
    v.forward(60)
    v.setheading(0)
    v.circle(100,70)
    v.forward(40)
    v.setheading(90)
    v.circle(80,160)
    v.setheading(90)
    v.forward(-30)
    v.setheading(-90)
    v.circle(100,70)
    v.forward(50)
    v.setheading(0)
    v.forward(50)
    v.setheading(0)
    v.circle(-100,80)
    v.setheading(0)
    v.goto(180,-180)
    v.setheading(-90)
    v.circle(100,80)
    v.setheading(0)
    v.forward(240)

# kiddie
def line1():
    tr.speed(50)
    tr.pensize(5)
    tr.penup()
    tr.goto(-475,-100)
    tr.pendown()
    tr.forward(200)
    tr.setheading(5)
    tr.circle(50,60)
    tr.setheading(-120)
    tr.circle(230,-125)
    tr.setheading(120)
    tr.circle(-25,-60)
    tr.setheading(0)
    tr.forward(250)
    # base
    tr.pensize(1)
    tr.penup()
    tr.goto(-470,-100)
    tr.pendown()
    tr.goto(-470,-400)
    tr.penup()
    tr.goto(-370,-100)
    tr.pendown()
    tr.goto(-370,-400)
    tr.penup()
    tr.goto(-270,-100)
    tr.pendown()
    tr.goto(-270,-400)
    tr.penup()
    tr.goto(-170,2)
    tr.pendown()
    tr.goto(-170,-400)
    tr.penup()
    tr.goto(-70,40)
    tr.pendown()
    tr.goto(-70,-400)
    tr.penup()
    tr.goto(30,30)
    tr.pendown()
    tr.goto(30,-400)
    tr.penup()
    tr.goto(130,-25)
    tr.pendown()
    tr.goto(130,-400)
    tr.penup()
    tr.goto(230,-100)
    tr.pendown()
    tr.goto(230,-400)
    tr.penup()
    tr.goto(330,-100)
    tr.pendown()
    tr.goto(330,-400)
    tr.penup()
    tr.goto(430,-100)
    tr.pendown()
    tr.goto(430,-400)
    tr.penup()
    tr.goto(-475,-400)
    tr.pendown()
    tr.pensize(5)
    tr.goto(475,-400)
    tr.penup()
    #ride the coaster
    print("WEEHEEEE!")
    # vehicle
    v = trtl.Turtle()
    vehicle = ("1.1.9/ihateyou (1).gif")
    wn.addshape(vehicle)
    v.shape(vehicle)
    v.speed(2)
    v.penup()
    v.goto(-475,-90)
    v.forward(200)
    v.setheading(5)
    v.circle(50,60)
    v.setheading(-120)
    v.circle(230,-125)
    v.setheading(120)
    v.circle(-25,-60)
    v.setheading(0)
    v.forward(250)

print("Welcome to Minion Mountain!")
# background image
wn.bgpic("1.1.9/ihateclouds2.gif")
#repeat program
redo = "y"
while (redo == "y"):
    #ask what coaster they want
    available_coasters ="1. Mid", "2. Intense", "3. Kiddie"
    print("Pick your rollar coaster:")
    for coaster in available_coasters:
        print(coaster)
        print()
    user_coaster = input("your choice: ")
    #add roller coaster type
    if(user_coaster == "1"):
        print()
        print("Woohoo! You picked the mid coaster, time to pick the color of your cart!")
    if(user_coaster == "2"):
        print()
        print("Woohoo! You picked the intense coaster, time to pick the color of your cart!")
    if(user_coaster == "3"):
        print()
        print("Woohoo! You picked the kiddie coaster, time to pick the color of your cart!")
    #add color
    available_colors ="1. red", "2. blue", "3. purple"
    for color in available_colors:
        print(color)
        print()
    user_color = input("Your Choice: ")
    #finally choice of color and coaster type
    if (user_coaster =="1") and (user_color =="1"):
        print()
        print("Here is the RED MID COASTER!")
        tr.pencolor("red")
        line3()
    if (user_coaster =="1") and (user_color =="2"):
        print()
        print("Here is the BLUE MID COASTER!!")
        tr.pencolor("blue")
        line3()
    if (user_coaster =="1") and (user_color =="3"):
        print()
        print("Here is the PURPLE MID COASTER!!")
        tr.pencolor("purple")
        line3()
    if (user_coaster =="2") and (user_color =="1"):
        print()
        print("Here is the RED INTENSE COASTER!!")
        tr.pencolor("red")
        line2()
    if (user_coaster =="2") and (user_color =="2"):
        print()
        print("Here is the BLUE INTENSE COASTER!!")
        tr.pencolor("blue")
        line2()
    if (user_coaster =="2") and (user_color =="3"):
        print()
        print("Here is the PURPLE INTENSE COASTER!!")
        tr.pencolor("purple")
        line2()
    if (user_coaster =="3") and (user_color =="1"):
        print()
        print("Here is the RED KIDDIE COASTER!!")
        tr.color("red")
        line1()
    if (user_coaster =="3") and (user_color =="2"):
        print()
        print("Here is the BLUE KIDDIE COASTER!!")
        tr.color("blue")
        line1()
    if (user_coaster =="3") and (user_color =="3"):
        print()
        print("Here is the PURPLE KIDDIE COSTER!")
        tr.color("purple")
        line1()
    redo = input("Do you want to pick another roller coaster? (y/n)")
    if (redo == "y"):
        tr.clear()
    if (redo == "n"):
        print("oh…ok…bye :(")
wn = trtl.Screen()
wn.mainloop()
